stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Building the project..."
  only:
    - backend

test_job:
  stage: test
  script:
    - echo "Running tests..."
  only:
    - backend
